spring:
  application.name:
    user-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:9999
        client-ip: 127.0.0.1
      eager: true
      http-method-specify: true
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      database: 0
#      connect-timeout: 5000ms
#      timeout: 5000ms
#      client-type: lettuce


  datasource:
    url: jdbc:mysql://localhost:3306/mall_user?useSSL=false&serverTimezone=UTC
    username: root
    password: Cs12356..
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.cs: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: logs/${spring.application.name}


# mybatis config
mybatis:
  mapper-locations:
    classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9006

debug: true

seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    type: nacos # 注册中心类型 nacos
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
      namespace: "" # namespace，默认为空
      group: DEFAULT_GROUP # 分组，默认是DEFAULT_GROUP
      application: seata-server # seata服务名称
#        username: nacos
#        password: nacos
  tx-service-group: save-order-group # 事务组名称
  service:
    vgroup-mapping: # 事务组与tc集群的映射关系
      save-order-group: default
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      namespace: ""
#      dataId: seataServer.properties